import { Book, Author, Category } from "./types";

export const categories: Category[] = [
  {
    id: "1",
    name: "Fiction",
    description: "Novels, short stories, and literary fiction",
    image: "/placeholder.svg",
    bookCount: 2,
  },
  {
    id: "2",
    name: "Non-Fiction",
    description: "Biography, history, science, and more",
    image: "/placeholder.svg",
    bookCount: 2,
  },
  {
    id: "3",
    name: "Mystery & Thriller",
    description: "Suspenseful and thrilling stories",
    image: "/placeholder.svg",
    bookCount: 2,
  },
  {
    id: "4",
    name: "Romance",
    description: "Love stories and romantic novels",
    image: "/placeholder.svg",
    bookCount: 2,
  },
  {
    id: "5",
    name: "Science Fiction",
    description: "Futuristic and imaginative stories",
    image: "/placeholder.svg",
    bookCount: 2,
  },
  {
    id: "6",
    name: "Self-Help",
    description: "Personal development and improvement",
    image: "/placeholder.svg",
    bookCount: 2,
  }
];

export const authors: Author[] = [
  {
    id: "1",
    name: "Sarah Johnson",
    bio: "Bestselling author of contemporary fiction with over 2 million books sold worldwide.",
    image: "/placeholder.svg",
    bookCount: 12,
    website: "https://sarahjohnson.com",
  },
  {
    id: "2",
    name: "Michael Chen",
    bio: "Award-winning science fiction writer known for his innovative storytelling.",
    image: "/placeholder.svg",
    bookCount: 8,
  },
  {
    id: "3",
    name: "Emma Davis",
    bio: "Romance novelist and New York Times bestselling author.",
    image: "/placeholder.svg",
    bookCount: 15,
  },
  {
    id: "4",
    name: "Robert Wilson",
    bio: "Master of mystery and suspense with 20 years of writing experience.",
    image: "/placeholder.svg",
    bookCount: 18,
  },
];

export const books: Book[] = [
  {
    _id: "1",
    title: "The Psychology of Money",
    author: "Morgan Housel",
    description:
      "Timeless lessons on wealth, greed, and happiness doing well with money isn?t necessarily about what you know. It?s about how you behave. And behavior is hard to teach, even to really smart people.",
    price: 289,
    originalPrice: 399,
    rating: 4.8,
    reviewCount: 342,
    category: "Self-Help",
    isbn: "XXX-X-XXXXXX-XX-X",
    publisher: "Harmony Books",
    publishedDate: "2024-01-15",
    pages: 252,
    language: "English",
    coverImage: "https://res.cloudinary.com/do30pfwn3/image/upload/v1765563405/money_bpnclq.webp",
    inStock: true,
    featured: true,
    bestseller: true,
    newRelease: false,
  },
  {
    _id: "2",
    title: "Black Holes: The Reith Lectures",
    author: "Stephen Hawking",
    description:
      "n 2016 Professor Stephen Hawking delivered the BBC Reith Lectures on a subject that has fascinated him for decades - black holes. In these flagship lectures the legendary physicist argues that if we could only understand black holes and how they challenge the very nature of space and time, we could unlock the secrets of the universe.",
    price: 122,
    rating: 4.6,
    reviewCount: 189,
    category: "Science Fiction",
    isbn: "XXX-X-XXXXXX-XX-X",
    publisher: "Future Press",
    publishedDate: "2023-11-03",
    pages: 80,
    language: "English",
    coverImage: "https://res.cloudinary.com/do30pfwn3/image/upload/v1765563355/blackholes_gc08v7.png",
    inStock: true,
    featured: true,
    bestseller: false,
    newRelease: true,
  },
  {
    _id: "3",
    title: "The Final Experiment",
    author: "Yogesh SY",
    description:
      "The Final Experiment | The Mystery Thriller of the Year | Witness the Fall of our World",
    price: 270,
    rating: 4.7,
    reviewCount: 278,
    category: "Mystery & Thriller",
    isbn: "XXX-X-XXXXXX-XX-X",
    publisher: "Love Stories Publishing",
    publishedDate: "2024-02-14",
    pages: 227,
    language: "English",
    coverImage: "https://res.cloudinary.com/do30pfwn3/image/upload/v1765563407/final_j0rq6z.png",
    inStock: true,
    featured: true,
    bestseller: false,
    newRelease: false,
  },
  {
    _id: "4",
    title: "The Alchemist",
    author: "Paulo Coelho",
    description:
      "This story, dazzling in its powerful simplicity and inspiring wisdom, is about an Andalusian shepherd boy named Santiago who travels from his homeland in Spain to the Egyptian desert in search of a treasure buried in the Pyramids. Along the way he meets a Gypsy woman, a man who calls himself.",
    price: 239,
    rating: 4.9,
    reviewCount: 456,
    category: "Fiction",
    isbn: "XXX-X-XXXXXX-XX-X",
    publisher: "Crime & Mystery Co.",
    publishedDate: "2023-09-22",
    pages: 172,
    language: "English",
    coverImage: "https://res.cloudinary.com/do30pfwn3/image/upload/v1765563406/the-alchemist_fkqebg.png",
    inStock: true,
    featured: false,
    bestseller: true,
    newRelease: false,
  },
  {
    _id: "5",
    title: "Ratan Tata: A Life ",
    author: "Thomas Mathew",
    description:
      "To create an Indian environment with fresh air to breathe, clean water to drink, nutritious food with no one left hungry, and a way to care for everyone’s health should be the priority for you and me.—Ratan Tata",
    price: 898,
    rating: 4.5,
    reviewCount: 123,
    category: "Non-Fiction",
    isbn: "XXX-X-XXXXXX-XX-X",
    publisher: "Wellness Books",
    publishedDate: "2024-03-01",
    pages: 712,
    language: "English",
    coverImage: "https://res.cloudinary.com/do30pfwn3/image/upload/v1765563383/ratan-tata_iwyfgo.png",
    inStock: true,
    featured: false,
    bestseller: false,
    newRelease: true,
  },
  {
    _id: "6",
    title: "Relativity",
    author: "Albert Einstein",
    description:
      "Relativity: The Special And The General Theory by Albert Einstein | Concepts of Physics, Relativity, General Relativity & Quantum Mechanics | Conceptual Physics, University Physics & Calculus Core.",
    price: 199,
    rating: 4.4,
    reviewCount: 87,
    category: "Science-Fiction",
    isbn: "XXX-X-XXXXXX-XX-X",
    publisher: "Academic Press",
    publishedDate: "2023-12-10",
    pages: 140,
    language: "English",
    coverImage: "https://res.cloudinary.com/do30pfwn3/image/upload/v1765563384/relativity_ms6cce.png",
    inStock: true,
    featured: false,
    bestseller: false,
    newRelease: false,
  },
  {
    _id: "7",
    title: "Stars Will Guide You Home",
    author: "Stuti Changle",
    description:
      "s teenagers, Kiana and Nirvaan were inseparable-until family expectations tore them apart.",
    price: 150,
    rating: 4.4,
    reviewCount: 87,
    category: "Fiction",
    isbn: "XXX-X-XXXXXX-XX-X",
    publisher: "Academic Press",
    publishedDate: "2023-12-10",
    pages: 226,
    language: "English",
    coverImage: "https://res.cloudinary.com/do30pfwn3/image/upload/v1765563439/stars_eyfz6u.png",
    inStock: true,
    featured: false,
    bestseller: false,
    newRelease: false,
  },
  {
    _id: "8",
    title: "Thinking fast & slow",
    author: "Daniel Kahneman ",
    description:
      "The book delineates rational and non-rational motivations or triggers associated with each type of thinking process, and how they complement each other, starting with Kahneman's own research on loss aversion.",
    price: 399,
    rating: 4.4,
    reviewCount: 87,
    category: "Science Fiction",
    isbn: "XXX-X-XXXXXX-XX-X",
    publisher: "Academic Press",
    publishedDate: "2023-12-10",
    pages: 320,
    language: "English",
    coverImage: "https://res.cloudinary.com/do30pfwn3/image/upload/v1765563406/thinking_ew2hqw.png",
    inStock: true,
    featured: false,
    bestseller: false,
    newRelease: false,
  },
  {
    _id: "9",
    title: "The stationary Shop Of Tehran",
    author: "Marjan Kamali",
    description:
      " A dreamy, idealistic teenager living amid the political upheaval of 1953 Tehran, finds a literary oasis in kindly Mr. Fakhri's neighborhood stationery shop.",
    price: 349,
    rating: 4.4,
    reviewCount: 87,
    category: "Non-Fiction",
    isbn: "XXX-X-XXXXXX-XX-X",
    publisher: "Academic Press",
    publishedDate: "2023-12-10",
    pages: 500,
    language: "English",
    coverImage: "https://res.cloudinary.com/do30pfwn3/image/upload/v1765563439/stationary_zjp20a.png",
    inStock: true,
    featured: false,
    bestseller: false,
    newRelease: false,
  },
  {
    _id: "10",
    title: "Master Your Emotions",
    author: "Thibaut Meurisse ",
    description:
      "Master Your Emotions is the ‘how-to’ manual your parents should have given you at birth. By reading it, you’ll learn how to deal with negative emotions so you can live a happier, more fulfilling life.",
    price: 289,
    rating: 4.4,
    reviewCount: 87,
    category: "Self-Help",
    isbn: "XXX-X-XXXXXX-XX-X",
    publisher: "Academic Press",
    publishedDate: "2023-12-10",
    pages: 224,
    language: "English",
    coverImage: "https://res.cloudinary.com/do30pfwn3/image/upload/v1765563407/master_qpw69l.png",
    inStock: true,
    featured: false,
    bestseller: false,
    newRelease: false,
  },
  {
    _id: "11",
    title: "The Perfect Murder",
    author: "Ruskin Bond ",
    description:
      " For the thing must be done without violence, without clues, without trace.Is the perfect murder ever possible?",
    price: 199,
    rating: 4.4,
    reviewCount: 87,
    category: "Mystery & Thriller",
    isbn: "XXX-X-XXXXXX-XX-X",
    publisher: "Academic Press",
    publishedDate: "2023-12-10",
    pages: 175,
    language: "English",
    coverImage: "https://res.cloudinary.com/do30pfwn3/image/upload/v1765563406/perfect-murder_zk6wsj.png",
    inStock: true,
    featured: false,
    bestseller: false,
    newRelease: false,
  },
  {
    _id: "12",
    title: "Falling in love again",
    author: " Ruskin Bond",
    description:
      "Falling in love again: Stories of Love and Romance",
    price: 234,
    rating: 4.4,
    reviewCount: 87,
    category: "Romance",
    isbn: "XXX-X-XXXXXX-XX-X",
    publisher: "Academic Press",
    publishedDate: "2023-12-10",
    pages: 197,
    language: "English",
    coverImage: "https://res.cloudinary.com/do30pfwn3/image/upload/v1765563356/falling_b6ls4v.png",
    inStock: true,
    featured: false,
    bestseller: false,
    newRelease: false,
  },
  {
    _id: "13",
    title: "The Enemy",
    author: "Sarah Adams",
    description:
      "Everything is fair in love and war. And this is war.",
    price: 240,
    rating: 4.4,
    reviewCount: 87,
    category: "Romance",
    isbn: "XXX-X-XXXXXX-XX-X",
    publisher: "Academic Press",
    publishedDate: "2023-12-10",
    pages: 256,
    language: "English",
    coverImage: "https://res.cloudinary.com/do30pfwn3/image/upload/v1765563356/enemy_pwlr0c.png",
    inStock: true,
    featured: false,
    bestseller: false,
    newRelease: false,
  },
];

export const featuredBooks = books.filter((book) => book.featured);
export const bestsellers = books.filter((book) => book.bestseller);
export const newReleases = books.filter((book) => book.newRelease);

export const getBooksByCategory = (categoryName: string) =>
  books.filter((book) => book.category === categoryName);

export const getBooksByAuthor = (authorName: string) =>
  books.filter((book) => book.author === authorName);

export const getBookById = (id: string) => books.find((book) => book._id === id);
 